In [ ]:
ls

# HD Training

In [ ]:
#%tb

import importlib
import argparse
from omegaconf import OmegaConf
import os.path as osp
from datasets.inference_dataset import *
from datasets import *
import torch 

args = {'source': 'nuscenes', 'target': 'semantickitti', 'cluster_cfg': './cfg/clust_cfg/cluster_20.yaml', 
        'model_cfg': './cfg/model_cfg/kp_sk_infer.yaml', 'data_cfg_path': './cfg/data_cfg', 'subsample': 1, 
        'save_pred_path': '/root/main/3DLabelProp/results_3DLabelProp', 'train_hd': True, 'test_hd': False, 
        'hd_param': './cfg/hd_param.yaml'}

cfg = OmegaConf.create(args)
cluster_cfg = OmegaConf.load(cfg.cluster_cfg)
model_cfg = OmegaConf.load(cfg.model_cfg)
cfg = OmegaConf.merge(cfg,cluster_cfg,model_cfg)

if __name__ == "__main__":
    #Get info relative to the set
    if cfg.source == "semantickitti":
        source_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti.yaml"))
        train_set = SemanticKITTI(source_data_cfg,'train')
    elif cfg.source == "nuscenes":
        source_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"nuscenes.yaml"))
        train_set = nuScenes(source_data_cfg,'train')
    else:
        raise  NameError('source dataset not supported')

    if cfg.target == "semantickitti":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti.yaml"))
        train_set_2 = SemanticKITTI(target_data_cfg,'train')
    elif cfg.target == "nuscenes":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"nuscenes.yaml"))
        train_set_2 = nuScenes(target_data_cfg,'train')
    elif cfg.target == "semanticposs":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semanticposs.yaml"))
        train_set_2 = SemanticPOSS(target_data_cfg,'train')
    elif cfg.target == "semantickitti-nuscenes":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti-nuscenes.yaml"))
        train_set_2 = SemanticKITTI_Nuscenes(target_data_cfg,'train')
    elif "pandaset" in cfg.target:
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,cfg.target+".yaml"))
        train_set_2 = Pandaset(target_data_cfg,'train')
    
    else:
        raise  NameError('target dataset not supported')

    #Get info relative to the model
    if cfg.architecture.model == "KPCONV":
        module = importlib.import_module('models.kpconv.kpconv')
        model_information = getattr(module, cfg.architecture.type)()
        model_information.num_classes = train_set.get_n_label()
        model_information.ignore_label = -1
        model_information.in_features_dim = model_cfg.architecture.n_features
        model_information.train_hd = cfg.train_hd
        from models.kpconv_model import SemanticSegmentationModel
        module = importlib.import_module('models.kpconv.architecture')
        model_type = getattr(module, cfg.architecture.type)
        model = SemanticSegmentationModel(model_information,cfg,model_type)
    elif cfg.architecture.model == "SPVCNN":
        module = importlib.import_module('models.spvcnn.spvcnn')
        model_information = getattr(module, cfg.architecture.type)
        model_information.num_classes = train_set.get_n_label()
        model_information.ignore_label = -1
        model_information.in_features_dim = model_cfg.architecture.n_features
        from models.spvcnn_model import SemanticSegmentationSPVCNNModel
        model = SemanticSegmentationSPVCNNModel(model_information,cfg)
    else:
        raise  NameError('model not supported')
        
    # Get HD info
    if cfg.train_hd:
        hd_cfg = OmegaConf.load(cfg.hd_param)
        cfg = OmegaConf.merge(cfg,hd_cfg) 
        from models.HD import OnlineHD
        #device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        device = torch.device("cpu")
        model_hd = OnlineHD(hd_cfg.n_features, hd_cfg.n_dimensions, hd_cfg.n_classes, epochs = hd_cfg.epochs, device=device)
        
    #print(cfg.hd_block_stop) #The parameters of hd are now part of cfg

    output_dataset = InferenceDataset(cfg,train_set,train_set_2,model, model_information, model_hd)
    #try:
    #    ius, miu = valid_dataset.compute_results()
    #except:
    if cfg.train_hd:
        output_dataset.compute_hd_dataset()
        
        # Define the path for the "HD" folder
        hd_folder = os.path.join(cfg.save_pred_path, 'HD')

        # Check if the "HD" folder exists
        if not os.path.exists(hd_folder):
            os.makedirs(hd_folder)
            print(f"Folder 'HD' created at {hd_folder}")
        else:
            print(f"Folder 'HD' already exists at {hd_folder}")

        # Define file names for saving the tensors
        weights_path = os.path.join(hd_folder, 'weights.pt')
        encoding_path = os.path.join(hd_folder, 'encoding.pt')

        # Save the tensors
        torch.save(model_hd.model.weight, weights_path)
        torch.save(model_hd.encoder.weight, encoding_path)

        print(f"Tensors saved in {hd_folder}")
    
    #ius, miu = output_dataset.compute_results() # The results are already there?
    #print(ius)
    #print(miu)

Model ready
Sequence:  ['00', '01', '02', '03', '04', '05', '06', '07', '09', '10']


Processing dataset semantickitti:   0%|                                                                                      | 0/10 [00:00<?, ?it/s]

Last:  004538.bin
Last:  004538



Sequence: 00, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]
                                                                                                                                                    

Last:  001099.bin
Last:  001099



Sequence: 01, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]

fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.22it/s]


torch.Size([996, 128])
Ignores tensor(905)
tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1,  8,  8, -1, 14, 14, 14, 14, 14, 13, -1, -1, -1, -1, 13, -1, 13, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -



fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.64it/s]


torch.Size([1345, 128])
Ignores tensor(0)
tensor([14, 14, 16,  ..., 14, 14, 16])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1345, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.38it/s]


torch.Size([1539, 128])
Ignores tensor(730)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([730, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1539, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([3050, 128])
Ignores tensor(100)
tensor([-1, -1, -1,  ..., 14, 14, 14])
device cpu
pad torch.Size([100, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([3050, 2000])




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.51it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([4945, 128])
Ignores tensor(25)
tensor([ 8,  8,  8,  ..., 14, 13, 14])
device cpu
pad torch.Size([25, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.32it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([4945, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1126, 128])
Ignores tensor(112)
tensor([14, 14, 14,  ..., -1, -1, -1])
device cpu
pad torch.Size([112, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.64it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1126, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.78it/s]


torch.Size([1594, 128])
Ignores tensor(359)
tensor([-1, -1, -1,  ..., 14, 14, 14])
device cpu
pad torch.Size([359, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1594, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([978, 128])
Ignores tensor(471)
tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, 14,
        13, 13, 13, 13, 13, -1, 13, 13, 14, 14, 14, 14, 14, 14, 13, 13, 14, 14,
        -1, -1, 13, -1, -1, -1, 14, 13, 13, 13, 14, 13, 13, 13, 13, 14, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, 13, 13, -1, -1, 14, -1, -1, -1, 14,
        14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 13, 13, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 13, -1, 13, -1, -1, -1, -1,
        -1, -1, -1,  8, 13,  8,  8, 13,  8, 14, 14, -1, 14, -1, 14, 14, 13, 13,
        13, 13, 13, 14, 14, 14, -1, 14, 14, 14, 13, 14, 14, 14, 14, 13, 14, 14,
        13, 14, 14, 13, 14, -1, -1, -1, -1, 13, -1, 13, -1, -1, -1, 13, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, 13, -1, -1, -1, -1, -1,  8,  8, 1

/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 17.48it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([978, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.02it/s]


torch.Size([906, 128])
Ignores tensor(160)
tensor([14, 14, -1, 14, -1, -1, 14, 14, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, 14, 14, 16, 16, 16,
        16, 16, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 16, 14, 14, 14, 14, 16, 16, 16, -1, -1, -1, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, -1, 14, 14, 14, 14, 14, 16, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, -1, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, -1, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, -1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, -1, 14, 14, 14, 14, 14, -1, 14, 14, 14, 14, 14, 14, 1



fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1064, 128])
Ignores tensor(33)
tensor([14, -1, -1,  ..., 14, 14, 14])
device cpu
pad torch.Size([33, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.32it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1064, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([858, 128])
Ignores tensor(826)
tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1,  8, -1, -1, -1, -1, -1, -1, -1, -1, -

/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.09it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([858, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1032, 128])
Ignores tensor(1032)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1032, 2000])


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.51it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1032, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([4218, 128])
Ignores tensor(0)
tensor([ 8,  8,  8,  ..., 14, 13, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.83it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([4218, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([874, 128])
Ignores tensor(829)
tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1,  8,  8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -

/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.93it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2303, 128])
Ignores tensor(14)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([14, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.95it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2303, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1045, 128])
Ignores tensor(1045)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1045, 2000])


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.24it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1045, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2671, 128])
Ignores tensor(45)
tensor([14, 14, 14,  ..., 13, 13, 13])
device cpu
pad torch.Size([45, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2671, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.08it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([546, 128])
Ignores tensor(498)
tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, -1,
        -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, 14, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, 16, -1,
        -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1,
        -1, -1, -1, -1, -1, 16, 16, -1, 16, -1, -1, -1, 16, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -

/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.04it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([546, 2000])
Finish fit




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.88it/s]

torch.Size([1084, 128])
Ignores tensor(1084)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1084, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1084, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2094, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2094, 2000])




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.81it/s]

Processing dataset semantickitti:  20%|███████████████▌                                                              | 2/10 [00:03<00:13,  1.75s/it]

Finish fit
Last:  004641.bin
Last:  004641



Sequence: 02, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]
                                                                                                                                                    

Last:  000790.bin
Last:  000790



Sequence: 03, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]

fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([10967, 128])
Ignores tensor(4)
tensor([14, 14, 14,  ..., 12, 10, 12])
device cpu
pad torch.Size([4, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([10967, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.11s/it]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.97it/s]

torch.Size([1347, 128])
Ignores tensor(12)
tensor([12, 12, 12,  ..., 14, 12, 12])
device cpu
pad torch.Size([12, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1347, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7520, 128])
Ignores tensor(60)
tensor([ 0,  0,  0,  ..., 12, 14, 12])
device cpu
pad torch.Size([60, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7520, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.38it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([3860, 128])
Ignores tensor(3)
tensor([14, 14, 14,  ..., 12, 14, 12])
device cpu
pad torch.Size([3, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([3860, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.63it/s]

Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([6518, 128])
Ignores tensor(0)
tensor([16, 16, 14,  ..., 14, 10, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.74it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([6518, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([3725, 128])
Ignores tensor(26)
tensor([14, 14, 14,  ..., 10, 14, 14])
device cpu
pad torch.Size([26, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([3725, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.68it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([9282, 128])
Ignores tensor(3)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([3, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([9282, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.29it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([12276, 128])
Ignores tensor(4)
tensor([ 8,  8,  8,  ..., 10, 10, 10])
device cpu
pad torch.Size([4, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([12276, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.23s/it]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.52it/s]

torch.Size([1375, 128])
Ignores tensor(14)
tensor([10, 13, 13,  ..., 14, 13, 14])
device cpu
pad torch.Size([14, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1375, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


torch.Size([1545, 128])
Ignores tensor(40)
tensor([15, 15, 15,  ..., 14, 14, 14])
device cpu
pad torch.Size([40, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1545, 2000])


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.72it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7915, 128])
Ignores tensor(3)
tensor([13, 13, 13,  ..., 14, 14, 14])
device cpu
pad torch.Size([3, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7915, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.23it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 28.72it/s]

torch.Size([659, 128])
Ignores tensor(650)
tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1,  8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([9168, 128])
Ignores tensor(6)
tensor([12, 12, 12,  ..., 12, 12, 12])
device cpu
pad torch.Size([6, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([9168, 2000])


# HD Forward

In [ ]:
#%tb

import importlib
import argparse
from omegaconf import OmegaConf
import os.path as osp
from datasets.inference_dataset import *
from datasets import *
import torch 

args = {'source': 'nuscenes', 'target': 'semantickitti', 'cluster_cfg': './cfg/clust_cfg/cluster_20.yaml', 
        'model_cfg': './cfg/model_cfg/kp_sk_infer.yaml', 'data_cfg_path': './cfg/data_cfg', 'subsample': 1, 
        'save_pred_path': '/root/main/3DLabelProp/results_3DLabelProp', 'train_hd': True, 'test_hd': False, 
        'hd_param': './cfg/hd_param.yaml'}

cfg = OmegaConf.create(args)
cluster_cfg = OmegaConf.load(cfg.cluster_cfg)
model_cfg = OmegaConf.load(cfg.model_cfg)
cfg = OmegaConf.merge(cfg,cluster_cfg,model_cfg)

if __name__ == "__main__":
    #Get info relative to the set
    if cfg.source == "semantickitti":
        source_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti.yaml"))
        train_set = SemanticKITTI(source_data_cfg,'train')
    elif cfg.source == "nuscenes":
        source_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"nuscenes.yaml"))
        train_set = nuScenes(source_data_cfg,'train')
    else:
        raise  NameError('source dataset not supported')

    if cfg.target == "semantickitti":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti.yaml"))
        train_set_2 = SemanticKITTI(target_data_cfg,'train')
    elif cfg.target == "nuscenes":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"nuscenes.yaml"))
        train_set_2 = nuScenes(target_data_cfg,'train')
    elif cfg.target == "semanticposs":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semanticposs.yaml"))
        train_set_2 = SemanticPOSS(target_data_cfg,'train')
    elif cfg.target == "semantickitti-nuscenes":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti-nuscenes.yaml"))
        train_set_2 = SemanticKITTI_Nuscenes(target_data_cfg,'train')
    elif "pandaset" in cfg.target:
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,cfg.target+".yaml"))
        train_set_2 = Pandaset(target_data_cfg,'train')
    
    else:
        raise  NameError('target dataset not supported')

    #Get info relative to the model
    if cfg.architecture.model == "KPCONV":
        module = importlib.import_module('models.kpconv.kpconv')
        model_information = getattr(module, cfg.architecture.type)()
        model_information.num_classes = train_set.get_n_label()
        model_information.ignore_label = -1
        model_information.in_features_dim = model_cfg.architecture.n_features
        model_information.train_hd = cfg.train_hd
        from models.kpconv_model import SemanticSegmentationModel
        module = importlib.import_module('models.kpconv.architecture')
        model_type = getattr(module, cfg.architecture.type)
        model = SemanticSegmentationModel(model_information,cfg,model_type)
    elif cfg.architecture.model == "SPVCNN":
        module = importlib.import_module('models.spvcnn.spvcnn')
        model_information = getattr(module, cfg.architecture.type)
        model_information.num_classes = train_set.get_n_label()
        model_information.ignore_label = -1
        model_information.in_features_dim = model_cfg.architecture.n_features
        from models.spvcnn_model import SemanticSegmentationSPVCNNModel
        model = SemanticSegmentationSPVCNNModel(model_information,cfg)
    else:
        raise  NameError('model not supported')
        
    # Get HD info
    if cfg.train_hd:
        hd_cfg = OmegaConf.load(cfg.hd_param)
        cfg = OmegaConf.merge(cfg,hd_cfg) 
        from models.HD import OnlineHD
        #device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        device = torch.device("cpu")
        model_hd = OnlineHD(hd_cfg.n_features, hd_cfg.n_dimensions, hd_cfg.n_classes, epochs = hd_cfg.epochs, device=device)
        
    #print(cfg.hd_block_stop) #The parameters of hd are now part of cfg

    output_dataset = InferenceDataset(cfg,train_set,train_set_2,model, model_information, model_hd)
    #try:
    #    ius, miu = valid_dataset.compute_results()
    #except:
    output_dataset.compute_dataset()
    ius, miu = output_dataset.compute_results() # The results are already there?
    print(ius)
    print(miu)