In [ ]:
ls

# HD Training

In [1]:
#%tb

import importlib
import argparse
from omegaconf import OmegaConf
import os.path as osp
from datasets.inference_dataset import *
from datasets import *
import torch 

args = {'source': 'nuscenes', 'target': 'semantickitti', 'cluster_cfg': './cfg/clust_cfg/cluster_20.yaml', 
        'model_cfg': './cfg/model_cfg/kp_sk_infer.yaml', 'data_cfg_path': './cfg/data_cfg', 'subsample': 1, 
        'save_pred_path': '/root/main/3DLabelProp/results_3DLabelProp', 'train_hd': True, 'test_hd': False, 
        'hd_param': './cfg/hd_param.yaml'}

cfg = OmegaConf.create(args)
cluster_cfg = OmegaConf.load(cfg.cluster_cfg)
model_cfg = OmegaConf.load(cfg.model_cfg)
cfg = OmegaConf.merge(cfg,cluster_cfg,model_cfg)

if __name__ == "__main__":
    #Get info relative to the set
    if cfg.source == "semantickitti":
        source_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti.yaml"))
        train_set = SemanticKITTI(source_data_cfg,'train')
    elif cfg.source == "nuscenes":
        source_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"nuscenes.yaml"))
        train_set = nuScenes(source_data_cfg,'train')
    else:
        raise  NameError('source dataset not supported')

    if cfg.target == "semantickitti":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti.yaml"))
        train_set_2 = SemanticKITTI(target_data_cfg,'train')
    elif cfg.target == "nuscenes":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"nuscenes.yaml"))
        train_set_2 = nuScenes(target_data_cfg,'train')
    elif cfg.target == "semanticposs":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semanticposs.yaml"))
        train_set_2 = SemanticPOSS(target_data_cfg,'train')
    elif cfg.target == "semantickitti-nuscenes":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti-nuscenes.yaml"))
        train_set_2 = SemanticKITTI_Nuscenes(target_data_cfg,'train')
    elif "pandaset" in cfg.target:
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,cfg.target+".yaml"))
        train_set_2 = Pandaset(target_data_cfg,'train')
    
    else:
        raise  NameError('target dataset not supported')

    #Get info relative to the model
    if cfg.architecture.model == "KPCONV":
        module = importlib.import_module('models.kpconv.kpconv')
        model_information = getattr(module, cfg.architecture.type)()
        model_information.num_classes = train_set.get_n_label()
        model_information.ignore_label = -1
        model_information.in_features_dim = model_cfg.architecture.n_features
        model_information.train_hd = cfg.train_hd
        from models.kpconv_model import SemanticSegmentationModel
        module = importlib.import_module('models.kpconv.architecture')
        model_type = getattr(module, cfg.architecture.type)
        model = SemanticSegmentationModel(model_information,cfg,model_type)
    elif cfg.architecture.model == "SPVCNN":
        module = importlib.import_module('models.spvcnn.spvcnn')
        model_information = getattr(module, cfg.architecture.type)
        model_information.num_classes = train_set.get_n_label()
        model_information.ignore_label = -1
        model_information.in_features_dim = model_cfg.architecture.n_features
        from models.spvcnn_model import SemanticSegmentationSPVCNNModel
        model = SemanticSegmentationSPVCNNModel(model_information,cfg)
    else:
        raise  NameError('model not supported')
        
    # Get HD info
    if cfg.train_hd:
        hd_cfg = OmegaConf.load(cfg.hd_param)
        cfg = OmegaConf.merge(cfg,hd_cfg) 
        from models.HD import OnlineHD
        #device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        device = torch.device("cpu")
        model_hd = OnlineHD(hd_cfg.n_features, hd_cfg.n_dimensions, hd_cfg.n_classes, epochs = hd_cfg.epochs, device=device)
        
    #print(cfg.hd_block_stop) #The parameters of hd are now part of cfg

    output_dataset = InferenceDataset(cfg,train_set,train_set_2,model, model_information, model_hd)
    #try:
    #    ius, miu = valid_dataset.compute_results()
    #except:
    output_dataset.compute_hd_dataset()
    
    #ius, miu = output_dataset.compute_results() # The results are already there?
    #print(ius)
    #print(miu)

Model ready
Sequence:  ['00', '01', '02', '03', '04', '05', '06', '07', '09', '10']


Processing dataset semantickitti:   0%|                                                                                      | 0/10 [00:00<?, ?it/s]

Last:  004538.bin
Last:  004538



Sequence: 00, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]
                                                                                                                                                    

Last:  001099.bin
Last:  001099



Sequence: 01, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]

fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.73it/s]


torch.Size([1084, 128])
Ignores tensor(1084)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1084, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1084, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2540, 128])
Ignores tensor(235)
tensor([16, -1, -1,  ..., 14, -1, 14])
device cpu
pad torch.Size([235, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2540, 2000])




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.29it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2262, 128])
Ignores tensor(14)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([14, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2262, 2000])




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.76it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1783, 128])
Ignores tensor(0)
tensor([16, 14, 13,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1783, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.03it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2025, 128])
Ignores tensor(56)
tensor([ 8,  8,  8,  ..., 13, 14,  8])
device cpu
pad torch.Size([56, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2025, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.68it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1722, 128])
Ignores tensor(1500)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1500, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1722, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.84it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1314, 128])
Ignores tensor(1243)
tensor([ 8,  8,  8,  ..., -1, -1, -1])
device cpu


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.25it/s]

pad torch.Size([1243, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1314, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([3187, 128])
Ignores tensor(24)
tensor([8, 8, 8,  ..., 8, 8, 8])
device cpu
pad torch.Size([24, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.30it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([3187, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1478, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 16, 13, 16])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.94it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1478, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([3305, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 16, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.33it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([3305, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1535, 128])
Ignores tensor(347)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([347, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.25it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1535, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1933, 128])
Ignores tensor(0)
tensor([ 8,  8,  8,  ...,  8, 16, 16])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.59it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1933, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([774, 128])
Ignores tensor(543)


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.55it/s]


tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1,  8,  8,  8, -1, 14, 14, 14, 14, -1, 14, 14,
        14, 13, 14, 13, 13, 13, -1, 13, 13, 13, 13, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, 14, 14, 14, 14, 14, 14, 13, 13, 13, 13, -1, 13, 13,
        13, -1, 13, -1, -1, -1, -1, -1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 13, -1, 13, 13, 13, 14, 13, -1, 14, 14, 13, 13, -1, 14, -1, -1, -1,
        -1, 14, -1, 13, -1, 14, -1, -1, 13, -1, -1, -1, 14, -1,  8, -1, -1,  8,
        -1, 14, -1, -1, 14, 14, -1, -1, -1, 14, 14, 14, -1, -1, 13, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 13, -1, -1, 13,
        -1, -1, 14, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1,  8, -1,
        -1, 14, -1,  8, -1, -1,  8,  8, 



fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.41it/s]


torch.Size([1032, 128])
Ignores tensor(1032)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1032, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1032, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1267, 128])
Ignores tensor(1083)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1083, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.22it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1267, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1029, 128])
Ignores tensor(1029)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1029, 2000])


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.68it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1029, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2473, 128])
Ignores tensor(100)
tensor([-1, 14, -1,  ..., 14, -1, 16])
device cpu
pad torch.Size([100, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2473, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.18it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.27it/s]


torch.Size([1202, 128])
Ignores tensor(169)
tensor([-1, -1, -1,  ..., -1, 14, -1])
device cpu
pad torch.Size([169, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1202, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1047, 128])
Ignores tensor(5)
tensor([ 8,  8,  8,  ..., 16, 13, 13])
device cpu
pad torch.Size([5, 2000])
Encoded ignored 

/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.66it/s]


MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1047, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1849, 128])
Ignores tensor(37)
tensor([ 8,  8,  8,  ..., 13, -1, 14])
device cpu
pad torch.Size([37, 2000])
Encoded ignored 

/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.07it/s]

MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1849, 2000])
Finish fit




Processing dataset semantickitti:  20%|███████████████▌                                                              | 2/10 [00:05<00:22,  2.83s/it]

Last:  004641.bin
Last:  004641



Processing dataset semantickitti:  30%|███████████████████████▍                                                      | 3/10 [00:07<00:16,  2.30s/it]

Last:  000790.bin
Last:  000790



Sequence: 03, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]

fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([9314, 128])
Ignores tensor(4)
tensor([10, 10, 10,  ..., 12,  8,  8])
device cpu
pad torch.Size([4, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([9314, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([12707, 128])
Ignores tensor(4)
tensor([10, 10, 12,  ..., 13, 12, 13])
device cpu
pad torch.Size([4, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([12707, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.28s/it]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5293, 128])
Ignores tensor(7)
tensor([12, 12, 12,  ..., 12, -1, 12])
device cpu
pad torch.Size([7, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.94it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5293, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([3725, 128])
Ignores tensor(26)
tensor([14, 14, 14,  ..., 10, 14, 14])
device cpu
pad torch.Size([26, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.34it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([3725, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2973, 128])
Ignores tensor(5)
tensor([10, 10, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([5, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2973, 2000])




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.17it/s]

Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([12859, 128])
Ignores tensor(23)
tensor([ 0,  0,  0,  ...,  9, 14, 14])
device cpu
pad torch.Size([23, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([12859, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.29s/it]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 22.92it/s]

torch.Size([810, 128])
Ignores tensor(654)
tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 15,
        15, 15, 15, 15, 14, 15, 14, 15, -1, -1, -1, 14, -1, -1, -1, -1, -1, -1,
        14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 15, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, 15,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, 14, 14, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, 14, -1, -1, -1, 15, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, 17, -1, 15, 15, -1, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([10951, 128])
Ignores tensor(3)
tensor([14, 14, 14,  ..., 14, 16, 14])
device cpu
pad torch.Size([3, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([10951, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.02s/it]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1618, 128])
Ignores tensor(40)
tensor([15, 15, 15,  ..., -1, 14, 14])
device cpu
pad torch.Size([40, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1618, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.00it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5582, 128])
Ignores tensor(3)
tensor([14, 14, 14,  ..., 14, 12, 14])
device cpu
pad torch.Size([3, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.90it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5582, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([6044, 128])
Ignores tensor(4)
tensor([10, 10, 10,  ..., 12, 13, 12])
device cpu
pad torch.Size([4, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.83it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([6044, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 31.13it/s]


torch.Size([602, 128])
Ignores tensor(539)
tensor([14, 14, 14, 14, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1,  8, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, 14, -1, -1,
        14, -1, -1, -1, 14, -1, 14, -1, 14, -1, -1, 10, -1, 14, -1, -1, -1, -1,
        14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 14, 14, -1, -1, -1, -1, -1, -1,  8, 14,  8, -1,  8, -1,
        -1,  8, -1, -1, -1,  8, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1,
        14,  8, -1,  8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -



fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7507, 128])
Ignores tensor(60)
tensor([ 0,  0,  0,  ..., 12, 12, 12])
device cpu
pad torch.Size([60, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7507, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.39it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.84it/s]

torch.Size([1021, 128])
Ignores tensor(9)
tensor([14, 14, 14,  ..., 12, 14, -1])
device cpu
pad torch.Size([9, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1021, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7849, 128])
Ignores tensor(18)
tensor([10, 10, 10,  ..., 10, 14, 10])
device cpu
pad torch.Size([18, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7849, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.36it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([9340, 128])
Ignores tensor(138)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([138, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([9340, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.07it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7582, 128])
Ignores tensor(0)
tensor([ 8,  8,  8,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7582, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.42it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2492, 128])
Ignores tensor(16)
tensor([14, 12, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([16, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.00it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2492, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1999, 128])
Ignores tensor(8)
tensor([14, -1, -1,  ..., 15, 10, 15])
device cpu
pad torch.Size([8, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.44it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1999, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7990, 128])
Ignores tensor(0)
tensor([12, 12, 12,  ..., 13, 12, 12])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7990, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.33it/s]

Processing dataset semantickitti:  40%|███████████████████████████████▏                                              | 4/10 [00:21<00:41,  6.89s/it]

Finish fit
Last:  000262.bin
Last:  000262



Sequence: 04, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]
                                                                                                                                                    

Last:  002756.bin
Last:  002756



Sequence: 05, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]

fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([8972, 128])
Ignores tensor(0)
tensor([10, 10, 13,  ..., 10, 10, 12])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([8972, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.21it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([4891, 128])
Ignores tensor(309)
tensor([10, 10, 10,  ..., -1, 10, -1])
device cpu
pad torch.Size([309, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.15it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([4891, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.84it/s]


torch.Size([2244, 128])
Ignores tensor(717)
tensor([14, 14, 14,  ..., 14, -1, -1])
device cpu
pad torch.Size([717, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2244, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.75it/s]


torch.Size([1236, 128])
Ignores tensor(526)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([526, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1236, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([8287, 128])
Ignores tensor(23)
tensor([14, 14,  8,  ..., 10, 14, 10])
device cpu
pad torch.Size([23, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."




Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([8287, 2000])
Finish fit


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.34it/s]


fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7890, 128])
Ignores tensor(617)
tensor([10,  8,  8,  ..., 12, 16, 15])
device cpu
pad torch.Size([617, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7890, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.30it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.22it/s]

torch.Size([1212, 128])
Ignores tensor(17)
tensor([11, 11, 11,  ..., 11, 11, 11])
device cpu
pad torch.Size([17, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1212, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5645, 128])
Ignores tensor(0)
tensor([10, 10,  8,  ...,  8, 10, 10])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5645, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.69it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([10285, 128])
Ignores tensor(6)
tensor([8, 8, 8,  ..., 8, 8, 8])
device cpu
pad torch.Size([6, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([10285, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.05s/it]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7442, 128])
Ignores tensor(7)
tensor([ 8,  8,  8,  ..., 10, 13, 10])
device cpu
pad torch.Size([7, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7442, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.32it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([6317, 128])
Ignores tensor(368)
tensor([11, 11, 11,  ...,  4,  4,  4])
device cpu
pad torch.Size([368, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([6317, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.54it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.35it/s]

torch.Size([933, 128])
Ignores tensor(477)
tensor([ 8,  8, 10, 10, -1, -1, -1, -1, -1, -1, -1, -1,  8,  8, -1, 13, 13, 14,
        10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 16, 16, 16, 14, -1,
        -1, -1, 16, 16, 16, 16, 16, 16, 12, -1, -1, 12, 12, -1, 12, 12, 10, 10,
         8,  8, 10, 10, 10, 10, -1, 10, 10, 13, 13, 10, 10, 10, 10, 10, 10, 10,
        10, 13, 10, 10, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         8,  8,  8,  8,  8,  8,  8,  8, -1, -1, -1, -1,  8, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 12, 10, 10, 10, 10, 10, 10, 10, 13, 13,  8, 13, 14, 10,
        10, 10, 13, 13, 13, 13, -1, 13, 10, 13, 13, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, 13, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, 12, -1, 14, 14, 14, 14, -1, 16, -1, 16, -1, 16, 15, 15,  8,  9,  9,
         9,  8, 12,  8,  8, -1, -1, -1, -1, -1, -1, 10, -1, -1, -1, -1, 10, -




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7445, 128])
Ignores tensor(13)
tensor([13, 13, 13,  ..., 10, 10, 10])
device cpu
pad torch.Size([13, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.48it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7445, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5917, 128])
Ignores tensor(10)
tensor([13, 13, 10,  ..., 13, 13, 13])
device cpu
pad torch.Size([10, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.89it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5917, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5612, 128])
Ignores tensor(34)
tensor([12, 12, 12,  ...,  8,  8,  8])
device cpu
pad torch.Size([34, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.88it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5612, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.41it/s]


torch.Size([1361, 128])
Ignores tensor(0)
tensor([11, 11, 11,  ..., 14, 11, 11])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1361, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([3960, 128])
Ignores tensor(953)
tensor([ 8,  8,  8,  ..., -1, 13, 13])
device cpu
pad torch.Size([953, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.29it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([3960, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([8015, 128])
Ignores tensor(0)
tensor([13, 13, 13,  ..., 13, 13, 13])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([8015, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.34it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([4638, 128])
Ignores tensor(0)
tensor([10, 10, 10,  ...,  8, 13,  8])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.52it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([4638, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([981, 128])
Ignores tensor(342)
tensor([11, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14,
        14, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, -1, 11, 11,
        11, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, 14, 11, 11, 11, 11, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, -1, 11, 11, 11, 11,
        11, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, 12, -1, 12, 12, 12, 12,
        12, 12, 12, 12, 12, 12, 11, 12, 12, 12, 11, 12, 12, 12, -1, -1, -1, -1,
        14, -1, -1, 14, 14, 14, 11, -1, 12, 12, 11, 12, 12, 12, 11, 11, 11, 11,
        11, 11, 11, -1, 12, 11, 11, 11, 11, -1, 14, -1, 14, 14, 14, 14, 11, 14,
        12, 14, -1, 14, 14, -1, 14, -1, 14, -1, 11, 14, -1, 14, 14, 14, -1, -

/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.91it/s]

Processing dataset semantickitti:  60%|██████████████████████████████████████████████▊                               | 6/10 [00:34<00:26,  6.65s/it]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([981, 2000])
Finish fit
Last:  001074.bin
Last:  001074



Processing dataset semantickitti:  70%|██████████████████████████████████████████████████████▌                       | 7/10 [00:34<00:14,  4.90s/it]

Last:  001095.bin
Last:  001095



Processing dataset semantickitti:  80%|██████████████████████████████████████████████████████████████▍               | 8/10 [00:34<00:07,  3.57s/it]

Last:  001589.bin
Last:  001589



Sequence: 09, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]

fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7145, 128])
Ignores tensor(1)
tensor([16, 16, 16,  ..., 14, 12, 12])
device cpu
pad torch.Size([1, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7145, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.41it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.97it/s]


torch.Size([794, 128])
Ignores tensor(90)
tensor([14, 14, 14, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 14, 13, 13, 13,
        13, -1, -1, -1, -1, -1, -1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 12, 12, 12, 12, 14, 14, 14, 14, 14, 14, 14, 14, -1, 12, -1, -1, 12,
        12, -1, 12, 12, 14, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 12, 12, 12, 12, 12, -1, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 12, 12, 12, 12, 12, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 12,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 14, 12, 14, 12, 12, 12, 12, 12, 12, 12, 12, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 12, 14, 14, 14, 14, 14,
        12, 12, 14, 12, 12, 14, 12, 12, 16, 12, 12, 14, 14, 14, -1, 12, 12, 12,
        12, -1, 14, 12, 12, -1, 12, 16, 12, 14, 14, 14, 12, -1, 12, 12, 12, -1,
        12, 12, 12, 14, -1, 12, 14, 12, 12, 12, 12, 14, 12, 12, 12, -1, 14, 12



fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5796, 128])
Ignores tensor(0)
tensor([16, 16, 16,  ..., 10, 16,  8])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.80it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5796, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2591, 128])
Ignores tensor(2443)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([2443, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2591, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.78it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([7447, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([7447, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.32it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([6340, 128])
Ignores tensor(72)
tensor([ 8,  8,  8,  ..., 12, 16, 12])
device cpu
pad torch.Size([72, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([6340, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.55it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([10382, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 16])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([10382, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.06it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 21.45it/s]


torch.Size([786, 128])
Ignores tensor(182)
tensor([14, -1, -1, -1, -1, -1, -1,  8, 10, 10, 10, 10, 10, 10, -1, -1,  8,  8,
         8, -1,  8,  8, 10, 10, 10, 14, 14, 14, 14, 14, 14, 16, 16, 14, 10, 14,
         8, 10, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 16,  8, 14,
        14, 14, 14, 14, 14, 14, 14, -1, 14, 14, 14, 14, 14, -1, -1, 14, -1, -1,
        -1, -1, -1, -1, 10, 10, 10, 10, 16, 14, 14, 14, -1, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, -1, 14, -1,
        -1, 14, 14, 14, 14, 14, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1,  8, -1, -1, 14, -1,
        -1, -1, -1, -1, 14, -1, -1, -1, 10, 14, 14, 10, -1, 16, 14,  8, 14, 14,
        -1,  8,  8, 10, 10, 14, 14, 14, 16, 10, -1, 14, 10,  8,  8,  8, 14,  8,
        -1, 16, 14,  8, 14, 14,  8, 16, 14, 10, 14, -1, 14, 16, 14, 16, 14, 14,
        -1, -1, -1, 14, 14, 16, 15, 14, 14, 10,  8,  8, 14,  8, 15,  8, 14, 1



fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1665, 128])
Ignores tensor(148)
tensor([ 8,  8,  8,  ..., 14, 14, 14])
device cpu
pad torch.Size([148, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1665, 2000])




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.26it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([4715, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.37it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([4715, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5054, 128])
Ignores tensor(0)
tensor([10, 16, 16,  ..., 10,  8, 16])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.12it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5054, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.22it/s]


torch.Size([2746, 128])
Ignores tensor(2657)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([2657, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2746, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5119, 128])
Ignores tensor(43)
tensor([16, 16, -1,  ..., 16, -1, -1])
device cpu
pad torch.Size([43, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.10it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5119, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.77it/s]


torch.Size([2102, 128])
Ignores tensor(1)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([1, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2102, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.42it/s]


torch.Size([2363, 128])
Ignores tensor(0)
tensor([14, 16, 14,  ..., 16, 16, 16])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2363, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5792, 128])
Ignores tensor(0)
tensor([16, 16, 16,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.92it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5792, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([4755, 128])
Ignores tensor(0)
tensor([10, 10, 10,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.28it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([4755, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([14026, 128])
Ignores tensor(10)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([10, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([14026, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.24s/it]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([9170, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([9170, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.23it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([8351, 128])
Ignores tensor(11)
tensor([10, 10, 10,  ...,  8,  8,  8])
device cpu
pad torch.Size([11, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([8351, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.33it/s]

Processing dataset semantickitti:  90%|██████████████████████████████████████████████████████████████████████▏       | 9/10 [00:47<00:06,  6.20s/it]

Finish fit
Last:  001191.bin
Last:  001191



Sequence: 10, subsample number 1/1:   0%|                                                                                     | 0/5 [00:00<?, ?it/s]

fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.90it/s]


torch.Size([1340, 128])
Ignores tensor(1205)
tensor([-1, 16, 16,  ..., -1, -1, -1])
device cpu
pad torch.Size([1205, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1340, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 24.35it/s]


torch.Size([766, 128])
Ignores tensor(725)
tensor([14, 14, 14, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, 14, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -



fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2855, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2855, 2000])




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.49it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2122, 128])
Ignores tensor(1)
tensor([16, 16, 16,  ..., 10,  8, 14])
device cpu
pad torch.Size([1, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2122, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.14it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5349, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.09it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5349, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([9335, 128])
Ignores tensor(0)
tensor([10, 10, 10,  ..., 16, 16, 16])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([9335, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.08it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2008, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.77it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2008, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5521, 128])
Ignores tensor(0)
tensor([10, 10, 10,  ..., 10, 10, 10])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.86it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5521, 2000])
Finish fit





fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 20.82it/s]


torch.Size([1013, 128])
Ignores tensor(1013)
tensor([-1, -1, -1,  ..., -1, -1, -1])
device cpu
pad torch.Size([1013, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1013, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.88it/s]


torch.Size([605, 128])
Ignores tensor(86)
tensor([16, 16, 16, 16, 16, 13, 13, 13, 13, 10, 10, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, 17, 17, 17, 17, 17, 17, -1, -1, -1, -1, -1, -1, 16, 16, -1, 13,
        16, 10, 13, 16, 16, 16, 13, 16, 10, 10, 13, 13, 13, 13,  8, 10, -1, 13,
        13, 13, 16, 10, 13, 10, 16, 13, 13, 13, 13, 16, 13,  8, 16, 13, 13, 16,
        13, 13, 13, 13, 10, 16, 10, 16, 10, -1, 13, 13, 10, 16, -1, 16, 10, -1,
        16, 16, 10, -1,  8, -1, 13, 16, 16, 16, 16, 13, 10, 16, -1, -1, -1, 13,
        -1, -1, 16, 13,  8, 13, -1, 10, -1, 16, 16, 13,  8, -1, 16, 10, 10, 13,
        17, -1, 16, 10, 10, 13, -1, 16,  8, 13, -1, 10, 10, 16, 13, 13, 17, 13,
        10, -1, 13, -1, -1, 10, 13, 13, 16, 13,  8, 13, 13, 10, 10, -1, 10, 13,
         8, 16,  8, 16, 10, 13,  8, 16, 16, 13, 13, 10, 13, 16, 10, 13, 16, 13,
        17, 16, 16, 10, 13, -1, 16, 10, 10, 13, 13, 16, 10, 13, 10, 16, 16, -1,
        -1, 16, 16, 10, 13, 10, 13,  8,  8, 13,  8, 13, 13, 13, 16,  8, -1, 10



fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([10047, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([10047, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.12it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5264, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 16, 16, 16])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.23it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5264, 2000])
Finish fit





fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([5089, 128])
Ignores tensor(0)
tensor([14,  8, 14,  ..., 16, 14, 16])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.32it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([5089, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1970, 128])
Ignores tensor(344)
tensor([ 8,  8,  8,  ..., 16, 14, 14])
device cpu
pad torch.Size([344, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.79it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1970, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([4392, 128])
Ignores tensor(19)
tensor([ 8,  8,  8,  ..., 16, 16, 16])
device cpu
pad torch.Size([19, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.45it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([4392, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."
fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.43it/s]

torch.Size([501, 128])
Ignores tensor(481)
tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, 16, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, 16, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([2758, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([2758, 2000])




fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.39it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([4344, 128])
Ignores tensor(0)
tensor([14, 16, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.57it/s]


Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([4344, 2000])
Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([3004, 128])
Ignores tensor(0)
tensor([14, 14, 14,  ..., 14, 14, 14])
device cpu
pad torch.Size([0, 2000])
Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([3004, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.95it/s]


Finish fit




fit:   0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]

torch.Size([1693, 128])
Ignores tensor(1)
tensor([14, 16, 16,  ..., 14, 14, 14])
device cpu
pad torch.Size([1, 2000])


/root/anaconda3/envs/3DLabelProp/lib/python3.7/site-packages/torchhd/tensors/map.py:375: UserWarning: The norm of a vector is nearly zero, this could indicate a bug.
  "The norm of a vector is nearly zero, this could indicate a bug."


fit: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.80it/s]

Encoded ignored MAPTensor(0., grad_fn=<AliasBackward0>)
Encoded torch.Size([1693, 2000])
Finish fit




Processing dataset semantickitti: 100%|█████████████████████████████████████████████████████████████████████████████| 10/10 [00:55<00:00,  5.60s/it]


# HD Forward

In [ ]:
#%tb

import importlib
import argparse
from omegaconf import OmegaConf
import os.path as osp
from datasets.inference_dataset import *
from datasets import *
import torch 

args = {'source': 'nuscenes', 'target': 'semantickitti', 'cluster_cfg': './cfg/clust_cfg/cluster_20.yaml', 
        'model_cfg': './cfg/model_cfg/kp_sk_infer.yaml', 'data_cfg_path': './cfg/data_cfg', 'subsample': 1, 
        'save_pred_path': '/root/main/3DLabelProp/results_3DLabelProp', 'train_hd': True, 'test_hd': False, 
        'hd_param': './cfg/hd_param.yaml'}

cfg = OmegaConf.create(args)
cluster_cfg = OmegaConf.load(cfg.cluster_cfg)
model_cfg = OmegaConf.load(cfg.model_cfg)
cfg = OmegaConf.merge(cfg,cluster_cfg,model_cfg)

if __name__ == "__main__":
    #Get info relative to the set
    if cfg.source == "semantickitti":
        source_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti.yaml"))
        train_set = SemanticKITTI(source_data_cfg,'train')
    elif cfg.source == "nuscenes":
        source_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"nuscenes.yaml"))
        train_set = nuScenes(source_data_cfg,'train')
    else:
        raise  NameError('source dataset not supported')

    if cfg.target == "semantickitti":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti.yaml"))
        train_set_2 = SemanticKITTI(target_data_cfg,'train')
    elif cfg.target == "nuscenes":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"nuscenes.yaml"))
        train_set_2 = nuScenes(target_data_cfg,'train')
    elif cfg.target == "semanticposs":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semanticposs.yaml"))
        train_set_2 = SemanticPOSS(target_data_cfg,'train')
    elif cfg.target == "semantickitti-nuscenes":
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,"semantic-kitti-nuscenes.yaml"))
        train_set_2 = SemanticKITTI_Nuscenes(target_data_cfg,'train')
    elif "pandaset" in cfg.target:
        target_data_cfg = OmegaConf.load(osp.join(cfg.data_cfg_path,cfg.target+".yaml"))
        train_set_2 = Pandaset(target_data_cfg,'train')
    
    else:
        raise  NameError('target dataset not supported')

    #Get info relative to the model
    if cfg.architecture.model == "KPCONV":
        module = importlib.import_module('models.kpconv.kpconv')
        model_information = getattr(module, cfg.architecture.type)()
        model_information.num_classes = train_set.get_n_label()
        model_information.ignore_label = -1
        model_information.in_features_dim = model_cfg.architecture.n_features
        model_information.train_hd = cfg.train_hd
        from models.kpconv_model import SemanticSegmentationModel
        module = importlib.import_module('models.kpconv.architecture')
        model_type = getattr(module, cfg.architecture.type)
        model = SemanticSegmentationModel(model_information,cfg,model_type)
    elif cfg.architecture.model == "SPVCNN":
        module = importlib.import_module('models.spvcnn.spvcnn')
        model_information = getattr(module, cfg.architecture.type)
        model_information.num_classes = train_set.get_n_label()
        model_information.ignore_label = -1
        model_information.in_features_dim = model_cfg.architecture.n_features
        from models.spvcnn_model import SemanticSegmentationSPVCNNModel
        model = SemanticSegmentationSPVCNNModel(model_information,cfg)
    else:
        raise  NameError('model not supported')
        
    # Get HD info
    if cfg.train_hd:
        hd_cfg = OmegaConf.load(cfg.hd_param)
        cfg = OmegaConf.merge(cfg,hd_cfg) 
        from models.HD import OnlineHD
        #device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        device = torch.device("cpu")
        model_hd = OnlineHD(hd_cfg.n_features, hd_cfg.n_dimensions, hd_cfg.n_classes, epochs = hd_cfg.epochs, device=device)
        
    #print(cfg.hd_block_stop) #The parameters of hd are now part of cfg

    output_dataset = InferenceDataset(cfg,train_set,train_set_2,model, model_information, model_hd)
    #try:
    #    ius, miu = valid_dataset.compute_results()
    #except:
    output_dataset.compute_dataset()
    ius, miu = output_dataset.compute_results() # The results are already there?
    print(ius)
    print(miu)